### ISSUE TITLE
Missing the database

### ISSUE THREAD

**Issue by baptisteroland** [aumbriac/php7-ajax-mysql-social-media-network#1]
Hi do you have the SQL file
Please

**Comment by aumbriac** [comment]
Hi,

I will work on putting one together for you. In the meantime, if you like
the project, could you please give it a star?

Thanks,
Anthony

**Comment by aumbriac** [comment]
Hi baptisteroland,

You can create the database by running this file on your localhost: https://github.com/aumbriac/php7-ajax-mysql-social-media-network/blob/master/create_db.php

Please let me know if you have any other issues
